default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_40453_development

test:
  <<: *default
  database: furima_40453_test

production:
  <<: *default
  database: furima_40453_production
  username: furima_40453
  password: <%= ENV["FURIMA_40453_DATABASE_PASSWORD"] %>
